# Tutorial 0 : Neural Process Family Framework

Last Update : 18 June 2020

**Aim**: 
- Brief overview of the framework (notation + computational perspective) I will use to try unifying different models from the neural process family
- introduce the datasets I will be using

## Preliminaries

### Notation

Let us denote a stochastic process as
$\mathrm{\mathbf{Y}} := \{ \mathrm{Y}^{(x)} \}_{x \in \mathcal{X}}$. $\mathcal{X}$ denotes an index set --- as it can be arbitrarily complex, we will usually refer to $x$ as a feature instead of indices ---, each random variable (r.v.) $\mathrm{Y}^{(x)}$ take value in (t.v.i) $\mathcal{Y}$ known as the state space.
$\mathrm{Y}$ is often thought of as a distribution over function, indeed sampling one outcome from each r.v. $\mathbf{y}:= \{ y^{(x)} \}_{x \in \mathcal{X}} \sim  \mathrm{\mathbf{Y}}$ gives rise to a function $f : \mathcal{X} \to \mathcal{Y}$ defined by the mapping $x \mapsto y^{(x)}$.
$\mathrm{Z}$ will be used for latent variables, $R$ will be used for temporary representations.

A key concept is the posterior predictive with density denoted as $p( \mathbf{y}_\mathcal{T} | \mathbf{y}_\mathcal{C}; \mathbf{x}_\mathcal{C}, \mathbf{x}_\mathcal{T})$.
Where $\mathrm{\mathbf{Y}}_{\mathcal{T}} := \big( \mathrm{Y}^{(x^{(t)})}\big)_{t=1}^T$ (resp.  $\mathrm{\mathbf{Y}}_{\mathcal{C}}$ ) is the collection of target (resp.) r.v. with possible outcome $\mathbf{y}_\mathcal{T}$ (resp. $\mathbf{y}_\mathcal{C}$) for the associated target features $\mathbf{x}_{\mathcal{T}} := \big( x^{(t)} \big)_{t=1}^T$(resp. context features  $\mathbf{x}_{\mathcal{C}}$).
For simplicity we will use the shorthand $\mathrm{Y}^{(t)} := \mathrm{Y}^{(x^{(t)})}$.

### Usecases of Stochastic Processes


We will be focusing on the following usecases of  stochastic processes can be useful:

* **Sampling from the prior predictive** $\mathbf{y}_{\mathcal{T}} \sim \mathrm{Y}_{\mathcal{T}}$.
This could be used for generating new functions (e.g. data augmentation, image generation ...).
* **Arg maximizing the posterior predictive** $\mathbf{y}_\mathcal{T}^* = \arg \max_{\mathbf{y}_\mathcal{T}'} p( \mathbf{y}_\mathcal{T}' | \mathbf{y}_\mathcal{C}; \mathbf{x}_\mathcal{C}, \mathbf{x}_\mathcal{T})$.
This can be used for imputing missing values, or meta-learning.
* **Sampling from the posterior predictive** $\mathbf{y}_{\mathcal{T}}  \sim \mathrm{Y}_{\mathcal{T}} | \mathrm{Y}_{\mathcal{C}}$.
This can be used for conditional generation .

### Gaussian Processes

We say that $\mathrm{\mathbf{Y}}$ is a GP if and only if any finite collection of r.v. $\{ \mathrm{Y}^{(x)} \}_{x \in \mathcal{X}' \subset \mathcal{X}}$ has a multivariate normal distribution.
This is especially interesting as each of the aforementioned usecases can be computed with closed form solutions.


\Cref{fig:GP_graphical_model} shows the probabilistic graphical model for a subset of r.v. from the GP (without plates : \cref{fig:GP_graphical_full_rasmussen}).
Note that predictions $y^{(t)}$ depend only on the outcome of the corresponding latent r.v. $z^{(t)}$.
The density of the posterior predictive is:

\[  p( \mathbf{y}_\mathcal{T} | \mathbf{y}_\mathcal{C}; \mathbf{x}_\mathcal{C}, \mathbf{x}_\mathcal{T}) = \int \prod_{t=1}^{T} p( y^{(t)} | z^{(t)}) \int  p( \mathbf{z}_\mathcal{C} | \mathbf{y}_\mathcal{C}; \mathbf{x}_\mathcal{C}) p( \mathbf{z}_\mathcal{T} | \mathbf{z}_\mathcal{C}; \mathbf{x}_\mathcal{C}, \mathbf{x}_\mathcal{T})   d  \mathbf{z}_\mathcal{C} d \mathbf{z}_\mathcal{T}   \]

Each term in the integral is a Gaussian density. 
Moreover, we normally assume that the prior has a constant mean and that observations have additive i.i.d Gaussian noise $y^{(x)} = z^{(x)} + \epsilon $.
In such case, the ``only important'' term is $p( \mathbf{z}_\mathcal{T} | \mathbf{z}_\mathcal{C}; \mathbf{x}_\mathcal{C}, \mathbf{x}_\mathcal{T})$, whose mean is a function of  $\mathbf{z}_\mathcal{C}$ but not its covariance.
Both the mean and the covariance are a function of the GP's kernel evaluated at combinations of $(\mathbf{x}_\mathcal{C}, \mathbf{x}_\mathcal{T})$.
Although the posterior predictive has a Gaussian density with mean and covaraince that can be computed in closed form, this requires inverting $K(\mathbf{x}_\mathcal{C},\mathbf{x}_\mathcal{C})$ which is $\mathcal{O}(C^3)$.

### Sparse Gaussian Processes

## Neural Process Family to Model Stochastic Processes

**Neural Processes Family (NPFs)** are a family of models which aim to model stochastic processes (distributions over functions) using neural networks.
If you think of neural networks as a way of approximating a function, then you can think of NPFs as a way of modeling a distribution over functions conditioned on a certain set of points (which we will call *context* set).
As a result, during training NPFs require a dataset of context sets of points instead of a set of points.
The links with meta-learning become immediately clear, but NPFs can also be used for generation, filling missing values, active learning ...


, which uses a set neural network to estimate the conditional predictive distribution $p(\mathrm{Y}_\mathcal{T} | \mathrm{X}_\mathcal{T}, \mathcal{C})$ over a set of *target* values $\mathrm{Y}_\mathcal{T} := \{\mathbf{y}^{(t)}\}_{t=1}^T$
conditioned on a set of corresponding target features $\mathrm{X}_\mathcal{T} := \{\mathbf{x}^{(t)}\}_{t=1}^T$ and a *context* set of feature-value pairs $\mathcal{C} := \{(\mathbf{x}^{(c)}, \mathbf{y}^{(c)})\}_{c=1}^C$ . 
Such conditional predictive distribution is usually modeled using stochastic process such as [Gaussian Processes (GPs)](https://en.wikipedia.org/wiki/Gaussian_process).
The idea of NPFs is to use neural networks instead, essentially trading off some ["well-behavedness" properties](#Lacking-Properties-of-NPFs) for  [computation ones](#Properties-of-NPFs).
In this series of notebooks, I will try to describe NPFs under a unifying framework. From a computation perspective, the family of models have three main components:

* The **encoder** $h_{\pmb{\theta}}$ takes as input a context point $(\mathbf{x}^{(c)}, \mathbf{y}^{(c)})$ and embeds it as $\mathbf{r}_c \in \mathbb{R}^d$. Typically, it is modeled as a multi-layer perceptron (MLP).

* The **aggregator** outputs a representation $\mathbf{r}_\mathcal{C}^{(t)} \in \mathbb{R}^d$ (or a distribution over $\mathbb{R}^d$), given all context embeddings $\{\mathbf{r}_c\}_{c=1}^C$ and a target features $\mathbf{x}^{(t)}$. As the input is an unordered set, the aggregator should be *permutation invariant* in $\mathcal{C}$.
A simple example of an aggregator is to use the average $\mathbf{r}_\mathcal{C}^{(t)} = \frac{1}{C} \sum_{c=1}^C \mathbf{r}_c$.

* The **decoder** predicts a distribution over target values $\mathbf{y}^{(t)}$, conditioned on $\mathbf{r}_\mathcal{C}^{(t)}$ and $\mathbf{x}^{(t)}$. This is achieved through a neural network $g_{\pmb\theta}$, which outputs sufficient statistics $\pmb\phi^{(t)}$ of a Gaussian probability density function (PDF).

### Formally

$$
\begin{align}
p(\mathrm{Y}_\mathcal{T} | \mathrm{X}_\mathcal{T}, \mathcal{C}) 
&\approx Q_{\pmb\theta}(\mathrm{Y}_\mathcal{T} | \mathrm{X}_\mathcal{T}, \mathcal{C}) & \text{Parametrization} \label{eq::cnp_approx}\tag{1} \\
&= \int p(z | \mathcal{C}) \prod_{t=1}^{T} Q_{\pmb\theta}(\mathbf{y}^{(t)} | \mathbf{x}^{(t)}, \mathcal{C}, \mathbf{z}) & \text{Exchangeability Assumption} \label{eq::cnp_factor}\tag{2} \\
&= \prod_{t=1}^{T} Q_{\pmb\theta}(\mathbf{y}^{(t)} | \mathbf{x}^{(t)}, \mathcal{C}) & \text{Factorization Assumption}  \label{eq::cnp_facto}\tag{3} \\
&= \prod_{t=1}^{T} Q_{\pmb\theta}(\mathbf{y}^{(t)} | \mathbf{x}^{(t)}, \mathbf{r}_\mathcal{C}^{(t)}) & \text{Sufficiency Assumption} \label{eq::cnp_rc}\tag{4} \\
&= \prod_{t=1}^{T} p(\mathbf{y}^{(t)} | \pmb\phi^{(t)})
\end{align}
$$

Where:

$$
\begin{align}
\mathbf{r}_c
&:= h_{\pmb\theta}(\mathbf{x}^{(c)}, \mathbf{y}^{(c)}) \label{eq::cnp_def_rc}
\\
\mathbf{r}_\mathcal{C}^{(t)}
&:= \mathrm{Agg}\left( \mathbf{x}^{(t)}, \{\mathbf{r}_c\}_{c=1}^{C} \right) \label{eq:cnp_def_agg}\\
\pmb\phi^{(t)} 
&:= g_{\pmb\theta}(  \mathbf{x}^{(t)},\mathbf{r}_\mathcal{C}^{(t)}) \label{eq::cnp_def_phi} \\
\end{align}
$$

with $\mathrm{Agg}$ being invariant to any permutations $\pi$ : $\mathrm{Agg}\left( \mathbf{x}^{(t)}, \{\mathbf{r}_c\}_{c=1}^{C} \right)=\mathrm{Agg}\left( \mathbf{x}^{(t)}, \pi\left(\{\mathbf{r}_{c}\}_{c=1}^{C} \right)\right)$


### Properties

#### Properties of NPFs

Properties that GPs also have:
* **Permutation Invariance in $\mathcal{C}$** : $Q_{\pmb\theta}(\mathrm{Y}_\mathcal{T} | \mathrm{X}_\mathcal{T}, \mathcal{C}) = Q_{\pmb\theta}(\mathrm{Y}_\mathcal{T} | \mathrm{X}_\mathcal{T}, \pi(\mathcal{C})), \forall \pi$. The predictive distribution does not depend on the ordering of the set of context points due to the permutation invariance of $\mathrm{Agg}$.
* **Permutation Equivariance in $(\mathrm{Y}_\mathcal{T}, \ \mathrm{X}_\mathcal{T})$** : $Q_{\pmb\theta}(\mathrm{Y}_\mathcal{T} | \mathrm{X}_\mathcal{T}, \mathcal{C}) = Q_{\pmb\theta}(\pi(\mathrm{Y}_\mathcal{T}) | \pi(\mathrm{X}_\mathcal{T}), \mathcal{C}), \forall \pi$. The predictive distribution does not depend on the ordering of the set of target points due to the conditional independence assumption $\mathbf{y}^{(t)} \perp \mathbf{y}^{(t')} | \{\mathbf{r}_\mathcal{C}^{(t)}\}_{t=1}^T, \ \forall t,t'$ made in \ref{eq::cnp_factor}. This is also known as (finite) **exchangeability**.

Properties that GPs do not have:
* **Data Driven Expressivity**. NPs require specification of prior knowledge through neural network architectures ($h_{\pmb\theta}$, $g_{\pmb\theta}$) rather than a kernel function (like in GPs).
The former is usually less restrictive due to its large amount of parameters and removing the need of satisfying certain mathematical properties. 
Intuitively, the NPs learn an "implicit kernel function" from the data.
* **Test-Time Scalability**. Although the computational complexity depends on which $\mathrm{Agg}$ is used, NPFs are more computationally efficient (at test time) than proper stochastic processes. This is essentially due to the sufficiency assumptions made in \ref{eq::cnp_rc}. I.e. the assumption that the context set $\mathcal{C}$ can be summarized by a fixed size representation $\mathbf{r}_\mathcal{C}^{(t)}$.
For example, inference in (C)NPs is $\mathcal{O}(T+C)$, in Attn(C)NPs it is $\mathcal{O}(C(T+C))$, in Conv(C)NPs it is $\mathcal{O}(N_{pseudo}(T+C))$, while in GPs it is $\mathcal{O}((T+C)^3)$.

#### Lacking Properties of NPFs

Important issues that NPFs have (at varying degrees depending on which model) but GPs don't:


* **Does not Satisfy Consistency Conditions**. Predictions are not guaranteed to be consistent, meaning that for $M<T$, the equality
\begin{equation}
Q_{\pmb\theta}(\{\mathbf{y}^{(t)}\}_{t=1}^M | \mathrm{X}_\mathcal{T}, \mathbf{r}_\mathcal{C}) 
= \int Q_{\pmb\theta}(\{\mathbf{y}^{(t)}\}_{t=1}^M, \{\mathbf{y}^{(t)}\}_{t=M+1}^T | \mathrm{X}_\mathcal{T}, \mathbf{r}_\mathcal{C}) d \mathbf{y}^{(M+1:T)}
\end{equation}
is not guaranteed to hold.
So NPFs are not proper stochastic processes.
This essentially means that even if you had infinite computational power and sampled points autoregressively, the order in which you do it would change the sampled set.
Putting aside the theoretical and conceptual issues, it is unclear to me how bad this is in practice (it might be).

* **The Need of Large Data**. Learning requires collecting and training on a large dataset of target and context points sampled from different functions. I.e. a large dataset of datasets.

* **Lack of Smoothness** Due to highly non linear behaviour of neural networks and the factorised form of the predictive distribution (\ref{eq::cnp_factor}), the output tends to be non-smooth compared to a GP.

### Training

The parameters are estimated by minimizing the expectation of the negative conditional conditional log likelihood .

$$\mathrm{NL}\mathcal{L}(\pmb{\theta}) := -\mathbb{E}_{\mathrm{X}_\mathcal{T}} \left[ \mathbb{E}_{\mathrm{Y}_\mathcal{T}} \left[ \mathbb{E}_{\mathcal{C}} \left[ \log Q_{\pmb\theta} \left(\mathrm{Y}_\mathcal{T} | \mathrm{X}_\mathcal{T}, \mathcal{C} \right)\right] \right]\right]$$

In practice we optimize it using stochastic gradient descent:

1. You sample a function $\{(\mathbf{x}^{(i)}, \mathbf{y}^{(i)})\}_{i} \sim P$ (abusing notation : $f \sim P$ ). E.g., a time serie, an image.
2. You sample some target and context set $\mathcal{T},\mathcal{C} \subset \{(\mathbf{x}^{(i)}, \mathbf{y}^{(i)})\}_{i}$ (abusing notation : $\mathcal{T},\mathcal{C} \sim f^C$ ). E.g., set of values (time serie) or set of pixels (image).
3. Compute the MC gradients of the negative (conditional) log likelihood $- \nabla_{\pmb \theta} \sum_{t=1}^T Q_{\pmb\theta}(\mathbf{y}^{(t)} | \mathbf{x}^{(t)}, \mathcal{C})$ 
4. Backpropagate


In practice, it means that training NPFs requires a dataset over datasets.


### NPFs Members

Let's quickly summarize some of the NPFs that we will be investigating

In [ ]:
import torch

In [30]:
x = torch.randn(3, 3) * 0.5
print(isin_range(x))
x

tensor(False)


tensor([[ 1.0473,  0.4335, -0.0693],
        [ 0.2483, -0.2876,  1.0110],
        [-0.0888, -0.0102,  0.3140]])

In [46]:
class Swallow:
    @property
    def airspeed(self):
        """Returns the airspeed (unladen)"""
        return 1

class AfricanSwallow:
    airspeed = Swallow.airspeed

In [47]:
af=AfricanSwallow()

In [54]:
t=torch.rand(1,2,3)
t

tensor([[[0.6475, 0.3834, 0.4815],
         [0.0320, 0.1933, 0.6603]]])

In [55]:
t.expand(1,2,3)

tensor([[[0.6475, 0.3834, 0.4815],
         [0.0320, 0.1933, 0.6603]]])

In [24]:
test(1)

1


In [25]:
def greeting(name: str) -> str:
    return 'Hello ' + name

In [26]:
greeting(1)

TypeError: can only concatenate str (not "int") to str